settings:
  legacy:
    force: true
    interval: 0s
schema:
- name: gofeedtomail
  path: .
  commands:
    build:
      status: true
      method: go build -race -o build/gofeedtomail-linux-amd64-dev src/main/main.go
    run:
      status: true
      method: build/gofeedtomail-linux-amd64-dev
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
